# -*- coding: utf-8 -*-
"""synthetic_data_code.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pglLuEeHzFn5woonrU0l2gRn90uMrWTu
"""

import pandas as pd
import numpy as np

# Synthetic Data Generation
data = {
    "Customer_ID": np.random.randint(1000,9999,500),
    "Age": np.random.randint(18,60,500),
    "Product_Category": np.random.choice(["Electronics","Clothing","Books","Home","Beauty","Sports"],500),
    "Purchase_Amount": np.random.randint(50,1000,500)
}

df = pd.DataFrame(data)


df.to_csv("amazon_synthetic_dataset.csv", index=False)

print("Synthetic dataset generated successfully!")
print(df.head())